name: Publish package

on:
  pull_request:
    types: [opened, closed]
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR event
        run: echo "Pull request event triggered!"