name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: github.actor
          server-password: ${{ secrets.TOKEN }}  # Gebruik hier je classic token
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Generate settings.properties file
        run: |
          echo "Genereren van settings.properties bestand..."
          # Genereer settings.properties met behulp van GitHub Secrets
          echo "baseURL=https://pot-gto.hdn.nl/api/v2" > settings.properties
          echo "authURL=https://auth-gto.hdn.nl" >> settings.properties
          echo "certificate=003059.p12" >> settings.properties
          echo "password=${{ secrets.SECRET_PASSWORD }}" >> settings.properties
          echo "publickeyUUID=3b44cf92-01f3-473e-89c6-1da43175b191" >> settings.properties
          echo "senderNode=003059" >> settings.properties
          echo "receiverNode=000372" >> settings.properties
          echo "processInterval=10" >> settings.properties
          echo "tokenInterval=500" >> settings.properties
          echo "clientID=hdn-pot-client" >> settings.properties
          echo "clientSecret=1507049c-c587-475d-821b-0b867b1bf8fb" >> settings.properties
          
          # Als je een certificaat als base64 nodig hebt:
          echo "Certificaat wordt gedecodeerd..."
          echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > 003059.p12

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -DaltDeploymentRepository=github::https://maven.pkg.github.com/Hypotheken-Data-Netwerk/hdn-platform-apiv2-client -Dusername=${{ github.actor }} -Dpassword=${{ secrets.TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Gebruik hier je classic token in plaats van het standaard GITHUB_TOKEN
